-- Veri Keşfi ve Marka Seçimi

SELECT DISTINCT BRAND FROM ITEMS;

SELECT BRAND, COUNT(*) AS NUMofITEMS
FROM ITEMS
GROUP BY BRAND
ORDER BY NUMofITEMS DESC;

SELECT *
INTO ITEMSofETI
FROM ITEMS
WHERE BRAND = 'ETI';

SELECT * FROM ITEMSofETI;